#Set to 0 to disable, higher to set the requirements
#Range: > 0
potion_sickness_req = 11
#Enable antidote recipe?
antidote_recipe = false
#Enable long_antidote recipe?
long_antidote_recipe = false
#Enable purity recipe?
purity_recipe = true
#Enable long_purity recipe?
long_purity_recipe = true
#Enable flight recipe?
flight_recipe = false
#Enable long_flight recipe?
long_flight_recipe = false
#Enable perplexity recipe?
perplexity_recipe = false
#Enable long_perplexity recipe?
long_perplexity_recipe = false
#Enable haste recipe?
haste_recipe = false
#Enable long_haste recipe?
long_haste_recipe = false
#Enable strong_haste recipe?
strong_haste_recipe = false
#Enable fatigue recipe?
fatigue_recipe = false
#Enable long_fatigue recipe?
long_fatigue_recipe = false
#Enable strong_fatigue recipe?
strong_fatigue_recipe = false
#Enable archery recipe?
archery_recipe = true
#Enable long_archery recipe?
long_archery_recipe = true
#Enable strong_archery recipe?
strong_archery_recipe = true
#Enable klutz recipe?
klutz_recipe = true
#Enable long_klutz recipe?
long_klutz_recipe = true
#Enable strong_klutz recipe?
strong_klutz_recipe = true
#Enable magic_focus recipe?
magic_focus_recipe = true
#Enable long_magic_focus recipe?
long_magic_focus_recipe = true
#Enable strong_magic_focus recipe?
strong_magic_focus_recipe = true
#Enable magic_inhibition recipe?
magic_inhibition_recipe = true
#Enable long_magic_inhibition recipe?
long_magic_inhibition_recipe = true
#Enable strong_magic_inhibition recipe?
strong_magic_inhibition_recipe = true
#Enable reach recipe?
reach_recipe = false
#Enable long_reach recipe?
long_reach_recipe = false
#Enable strong_reach recipe?
strong_reach_recipe = false
#Enable recoil recipe?
recoil_recipe = true
#Enable long_recoil recipe?
long_recoil_recipe = true
#Enable strong_recoil recipe?
strong_recoil_recipe = true
#Enable repair recipe?
repair_recipe = true
#Enable long_repair recipe?
long_repair_recipe = true
#Enable strong_repair recipe?
strong_repair_recipe = true
#Enable rust recipe?
rust_recipe = true
#Enable long_rust recipe?
long_rust_recipe = true
#Enable strong_rust recipe?
strong_rust_recipe = true
#Enable solid_core recipe?
solid_core_recipe = true
#Enable long_solid_core recipe?
long_solid_core_recipe = true
#Enable strong_solid_core recipe?
strong_solid_core_recipe = true
#Enable spin recipe?
spin_recipe = false
#Enable long_spin recipe?
long_spin_recipe = false
#Enable strong_spin recipe?
strong_spin_recipe = false
#Enable step_up recipe?
step_up_recipe = true
#Enable long_step_up recipe?
long_step_up_recipe = true
#Enable strong_step_up recipe?
strong_step_up_recipe = true
#Enable vulnerable recipe?
vulnerable_recipe = true
#Enable long_vulnerable recipe?
long_vulnerable_recipe = true
#Enable strong_vulnerable recipe?
strong_vulnerable_recipe = true
#Enable nausea recipe?
nausea_recipe = false
#Enable long_nausea recipe?
long_nausea_recipe = false
#Enable chance recipe?
chance_recipe = true
#Enable strong_chance recipe?
strong_chance_recipe = true
#Enable bless recipe?
bless_recipe = true
#Enable strong_bless recipe?
strong_bless_recipe = true
#Enable curse recipe?
curse_recipe = true
#Enable strong_curse recipe?
strong_curse_recipe = true
#Enable cure recipe?
cure_recipe = true
#Enable dispel recipe?
dispel_recipe = false
#Enable wither recipe?
wither_recipe = false
#Enable long_wither recipe?
long_wither_recipe = false
#Enable strong_wither recipe?
strong_wither_recipe = false
#Enable love recipe?
love_recipe = true
#Enable long_love recipe?
long_love_recipe = true
#Enable strong_love recipe?
strong_love_recipe = true
#Enable iron_skin recipe?
iron_skin_recipe = true
#Enable long_iron_skin recipe?
long_iron_skin_recipe = true
#Enable strong_iron_skin recipe?
strong_iron_skin_recipe = true
#Enable diamond_skin recipe?
diamond_skin_recipe = true
#Enable long_diamond_skin recipe?
long_diamond_skin_recipe = true
#Enable strong_diamond_skin recipe?
strong_diamond_skin_recipe = true
#Enable broken_armor recipe?
broken_armor_recipe = true
#Enable long_broken_armor recipe?
long_broken_armor_recipe = true
#Enable strong_broken_armor recipe?
strong_broken_armor_recipe = true
#Enable climb recipe?
climb_recipe = true
#Enable long_climb recipe?
long_climb_recipe = true
#Enable magic_shield recipe?
magic_shield_recipe = true
#Enable long_magic_shield recipe?
long_magic_shield_recipe = true
#Enable strong_magic_shield recipe?
strong_magic_shield_recipe = true
#Enable broken_magic_shield recipe?
broken_magic_shield_recipe = true
#Enable long_broken_magic_shield recipe?
long_broken_magic_shield_recipe = true
#Enable strong_broken_magic_shield recipe?
strong_broken_magic_shield_recipe = true
#Enable drown recipe?
drown_recipe = true
#Enable long_drown recipe?
long_drown_recipe = true
#Enable strong_drown recipe?
strong_drown_recipe = true
#Enable revival recipe?
revival_recipe = true
#Enable long_revival recipe?
long_revival_recipe = true
#Enable strong_revival recipe?
strong_revival_recipe = true
#Enable weight recipe?
weight_recipe = true
#Enable long_weight recipe?
long_weight_recipe = true
#Enable strong_weight recipe?
strong_weight_recipe = true
#Enable lightning recipe?
lightning_recipe = true
#Enable invert recipe?
invert_recipe = false
#Enable fire recipe?
fire_recipe = true
#Enable long_fire recipe?
long_fire_recipe = true
#Enable extend recipe?
extend_recipe = true
#Enable long_extend recipe?
long_extend_recipe = true
#Enable launch recipe?
launch_recipe = true
#Enable strong_launch recipe?
strong_launch_recipe = true
#Enable explosion recipe?
explosion_recipe = true
#Enable strong_explosion recipe?
strong_explosion_recipe = true
#Enable burst recipe?
burst_recipe = true
#Enable strong_burst recipe?
strong_burst_recipe = true
#Enable random_teleport recipe?
random_teleport_recipe = true
#Enable strong_random_teleport recipe?
strong_random_teleport_recipe = true
#Enable surface_teleport recipe?
surface_teleport_recipe = true
#Enable spawn_teleport recipe?
spawn_teleport_recipe = true

