#Disable wool drops to force the player to get shears.
disableWoolDrops = true
#Reset all skills to 1 when a player dies.
deathSkillReset = false
#Toggle the visibility of the tab buttons in the inventory.
showTabButtons = false
#Starting cost of upgrading to level 2, in experience points.
#Range: 0 ~ 1000
startingCost = 7
#Global scaling multiplier for XP costs.
#Range: 0.1 ~ 10.0
xpScalingMultiplier = 1.0
#Maximum level each skill can be upgraded to.
#Range: 2 ~ 100
maximumLevel = 32
skillAliases = ["defense=defense"]
#List of substitutions to perform in names in skill lock lists.
#Useful if you're using a resource pack to change the names of skills, this config doesn't affect gameplay, just accepted values in other configs so it's easier to think about
#Format: key=value
#Valid values: attack, defense, mining, gathering, farming, building, agility, magic
#Enable or disable skill leveling via GUI or selection. If disabled, skill levels must be granted by commands.
enableSkillLeveling = true
#Enable or disable the skill level-up message.
enableSkillUpMessage = true

