
[gui]
	#The offset of the left of the thirst overlay from its default position.
	thirst_left_offset = 0
	#The offset of the top of the thirst overlay from its default position.
	thirst_top_offset = 0
	#The offset of the left of the temperature overlay from its default position.
	temperature_left_offset = 0
	#The offset of the top of the temperature overlay from its default position.
	temperature_top_offset = 0

